// send-team-report Edge Function
// Sends team performance report via email
// TODO: Integrate with SendGrid/Resend for actual email delivery

import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.0'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface ReportData {
  rep: string
  period: string
  totalDeals: number
  activeDeals: number
  closedWon: number
  closedLost: number
  pipelineValue: number
  wonValue: number
  notes?: string
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const reportData: ReportData = await req.json()

    // Get JWT and verify caller
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) throw new Error('Missing authorization header')

    const jwt = authHeader.replace('Bearer ', '')
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      { auth: { autoRefreshToken: false, persistSession: false } }
    )

    const { data: { user: authUser }, error: authError } = await supabaseAdmin.auth.getUser(jwt)
    if (authError || !authUser) {
      throw new Error('Unauthorized')
    }

    const { data: caller } = await supabaseAdmin
      .from('users')
      .select('role, name, email, org_id')
      .eq('id', authUser.id)
      .single()

    if (!caller || !['super_admin', 'admin', 'admin_m', 'sdr'].includes(caller.role)) {
      throw new Error('Unauthorized: only supervisors can send reports')
    }

    console.log('[send-team-report] Generating report for:', reportData.rep)

    // Generate email content
    const emailHtml = `
      <h2>Team Performance Report</h2>
      <p><strong>Rep:</strong> ${reportData.rep}</p>
      <p><strong>Period:</strong> ${reportData.period}</p>
      <hr>
      <h3>Summary</h3>
      <ul>
        <li><strong>Total Deals:</strong> ${reportData.totalDeals}</li>
        <li><strong>Active Deals:</strong> ${reportData.activeDeals}</li>
        <li><strong>Closed Won:</strong> ${reportData.closedWon} (${formatCurrency(reportData.wonValue)})</li>
        <li><strong>Closed Lost:</strong> ${reportData.closedLost}</li>
        <li><strong>Pipeline Value:</strong> ${formatCurrency(reportData.pipelineValue)}</li>
      </ul>
      ${reportData.notes ? `<hr><h3>Notes</h3><p>${reportData.notes}</p>` : ''}
      <hr>
      <p style="color: #666; font-size: 0.85em;">Generated by ${caller.name || caller.email} via IGNITE_APEX Team Reports</p>
    `

    // TODO: Integrate with SendGrid/Resend
    // For now, just log and return success
    console.log('[send-team-report] Email content generated:', emailHtml)

    // TODO: Actual email sending
    // const emailResult = await sendEmail({
    //   to: caller.email,
    //   cc: [adminEmail, repEmail],
    //   subject: `Team Report: ${reportData.rep} - ${reportData.period}`,
    //   html: emailHtml
    // })

    return new Response(
      JSON.stringify({
        success: true,
        message: 'Report generated successfully. Email functionality pending integration.',
        preview: emailHtml
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error('[send-team-report] Error:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
    )
  }
})

function formatCurrency(value: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0
  }).format(value || 0)
}
